---
root: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

overrides:
  - files:
      - test/**
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    rules:
      jest/prefer-expect-assertions: 'off'

parser: '@typescript-eslint/parser'

parserOptions:
  project:
    - ./tsconfig.json

plugins:
  - '@typescript-eslint'

rules: {}
