---
name: Lint Kubernetes manifests
description: Lint Kubernetes manifests

inputs:
  manifests:
    description: Newline-delimited paths to the manifest files
    required: true
  lint-type:
    description: |
      Allowed values: `kubeconform`, `dry-run`

      Please ensure you have set up a Kubernetes cluster in the workflow before this action, if using `dry-run`.
    required: true
    default: kubeconform

  kubeconform-options:
    description: Options passed to `kubeconform` (e.g. `-schema-location`)
    required: false
    default: -summary
  namespace:
    description: |
      Target Kubernetes namespace.

      If the namespace is not provided, commands will run with the `default` namespace.
    required: false
    default: default

runs:
  using: node20
  main: dist/index.js

branding:
  color: blue
  icon: life-buoy
