name: 'Lint k8s manifest files'
description: 'Lint k8s manifest files'
inputs:
   # Please ensure you have used either azure/k8s-actions/aks-set-context or azure/k8s-actions/k8s-set-context in the workflow before this action if using dryrun
   manifests:
      description: 'Path to the manifest files which will be used for deployment.'
      required: true
   lintType:
      description: 'Acceptable values: kubeconform, dryrun'
      required: true
      default: 'kubeconform'
   kubeconformOpts:
      description: 'Options that are passed to kubeconform e.g. -schema-location'
      required: false
      default: '-summary'
   namespace:
      description: 'Target Kubernetes namespace. If the namespace is not provided, commands will run in the default namespace.'
      required: false
      default: 'default'

branding:
   color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
   using: 'node20'
   main: 'lib/index.js'
