blank_issues_enabled: false
contact_links:
   - name: GitHub Action "k8s-lint" Support
     url: https://github.com/Azure/k8s-lint
     security: https://github.com/Azure/k8s-lint/blob/main/SECURITY.md
     about: Please ask and answer questions here.
