name: "Trigger Integration tests"
on:
  pull_request:

jobs:
  minikube-integration-tests:
    name: Minikube Integration Tests
    runs-on: ubuntu-22
    env:
      KUBECONFIG: /home/runner/.kube/config
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - id: setup-minikube
        name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: "v1.24.0"
          kubernetes version: "v1.17.8"
          driver: "none"
      - uses: actions/checkout@v3
      - id: action-npm-build
        name: Npm install and build
        run: |
          echo $PR_BASE_REF
          if [[ $PR_BASE_REF != releases/* ]]; then
            npm install
            npm run build
          fi

      # valid manifests
      - name: Execute k8s-lint with valid kubeval
        uses: ./
        with:
          manifests: |
            test/valid-ingress.yml
            test/valid-service.yml
      - name: Execute k8s-lint with valid dryrun
        uses: ./
        with:
          lintType: dryrun
          manifests: |
            test/valid-ingress.yml
            test/valid-service.yml

      # invalid manifests
      - name: Execute k8s-lint with invalid kubeval
        id: invalidKubeval
        continue-on-error: true
        uses: ./
        with:
          manifests: |
            test/invalid-ingress.yml
            test/invalid-service.yml
      - name: Execute k8s-lint with invalid dryrun
        id: invalidDryrun
        continue-on-error: true
        uses: ./
        with:
          lintType: dryrun
          manifests: |
            test/invalid-ingress.yml
            test/invalid-service.yml
      - name: Verify invalid dryruns
        if: steps.invalidKubeval.outcome != 'failure' || steps.invalidDryrun.outcome != 'failure'
        run: exit 1
