---
name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  minikube-integration-tests:
    name: Minikube Integration Tests

    runs-on: ubuntu-22.04
    env:
      KUBECONFIG: /home/runner/.kube/config
      VALID_MANIFESTS: |
        test/valid-ingress.yaml
        test/valid-service.yaml
      INVALID_MANIFESTS: |
        test/invalid-ingress.yml
        test/invalid-service.yml

    strategy:
      fail-fast: false
      matrix:
        kubernetes-version:
          - 1.28.3

    steps:
      - name: Setup minikube
        uses: medyagh/setup-minikube@fb886c58d699f41bd6e7c7bb41cdb6eab5e15042
        with:
          driver: none
          minikube-version: 1.31.2

          kubernetes-version: ${{ matrix.kubernetes-version }}
        timeout-minutes: 3

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Install and build
        shell: bash
        run: |
          pr_base_ref="${{ github.event.pull_request.base.ref }}"
          echo "${pr_base_ref}"
          if [[ "${pr_base_ref}" != releases/* ]]; then
            npm ci
            npm run build
          fi

      - name: Execute k8s-lint (kubeconform) with valid manifests
        uses: ./
        with:
          manifests: ${{ env.VALID_MANIFESTS }}
      - name: Execute k8s-lint (dry-run) with valid manifests
        uses: ./
        with:
          lintType: dry-run
          manifests: ${{ env.VALID_MANIFESTS }}

      - name: Execute k8s-lint (kubeconform) with invalid manifests
        id: invalid-kubeconform
        uses: ./
        continue-on-error: true
        with:
          manifests: ${{ env.INVALID_MANIFESTS }}
      - name: Execute k8s-lint (dry-run) with invalid manifests
        id: invalid-dry-run
        uses: ./
        continue-on-error: true
        with:
          lintType: dry-run
          manifests: ${{ env.INVALID_MANIFESTS }}

      - name: Verify invalid tests
        if: steps.invalid-kubeconform.outcome != 'failure' || steps.invalid-dry-run.outcome != 'failure'
        shell: bash
        run: exit 1
